@extends('layouts.market')
@push('styles')<style>.sidebar .nav-side:first-of-type a:first-child{display:none}form.card .col-md-3:has(select[name="status"]){display:none}#pengelola+.card th:nth-child(6),#pengelola+.card td:nth-child(6),#pedagang+.card th:nth-child(7),#pedagang+.card td:nth-child(7){display:none}</style>@endpush
@section('title','Bidang Pasar') @section('header','Bidang Pasar')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><h1 class="section-title">Data Pengelola dan Pedagang Pasar</h1><div class="section-subtitle">Pendataan dan rekap pelaku usaha pasar.</div></div>@if(auth()->user()->hasPermission('market_data.export'))<a href="{{ route('market-data.excel') }}" class="btn btn-success"><i class="bi bi-file-earmark-excel me-1"></i> Export Excel</a>@endif</div>
<form class="card mb-4"><div class="card-body"><div class="row g-2 align-items-end"><div class="col-md-6"><label class="form-label">Pencarian</label><input type="search" name="q" value="{{ $search }}" class="form-control" list="marketSuggestions" placeholder="Nama perusahaan, toko, kontak, atau bidang usaha"><datalist id="marketSuggestions">@foreach($suggestions as $suggestion)<option value="{{ $suggestion }}">@endforeach</datalist></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Semua status</option>@foreach(['submitted'=>'Menunggu Verifikasi','verified'=>'Terverifikasi','rejected'=>'Ditolak'] as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-primary">Tampilkan</button></div>@if($search||$status)<div class="col-auto"><a href="{{ route('market-data.index') }}" class="btn btn-light border">Reset</a></div>@endif</div></div></form>
@if(auth()->user()->hasPermission('market_data.create'))
<div class="row g-4 mb-4"><div class="col-xl-6"><div class="card h-100"><div class="card-header"><strong>{{ $editingManager ? 'Edit' : 'Tambah' }} Data Pengelola</strong></div><div class="card-body"><form method="post" action="{{ $editingManager ? route('market-data.managers.update',$editingManager) : route('market-data.managers.store') }}">@csrf @if($editingManager)@method('put')@endif<div class="row g-3"><div class="col-md-6"><label class="form-label">Nama Perusahaan</label><input name="nama_perusahaan" value="{{ old('nama_perusahaan',$editingManager?->nama_perusahaan) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Kontak Person</label><input name="kontak_person" value="{{ old('kontak_person',$editingManager?->kontak_person) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Nomor Telepon</label><input name="no_telepon" value="{{ old('no_telepon',$editingManager?->no_telepon) }}" class="form-control" inputmode="tel" required></div><div class="col-md-6"><label class="form-label">Kapasitas Tenant</label><input type="number" min="0" name="kapasitas_tenant" value="{{ old('kapasitas_tenant',$editingManager?->kapasitas_tenant) }}" class="form-control"></div><div class="col-12"><label class="form-label">Alamat</label><textarea name="alamat" class="form-control" required>{{ old('alamat',$editingManager?->alamat) }}</textarea></div><div class="col-12 text-end">@if($editingManager)<a href="{{ route('market-data.index') }}" class="btn btn-light border me-2">Batal</a>@endif<button class="btn btn-primary">{{ $editingManager ? 'Simpan Perubahan' : 'Simpan Pengelola' }}</button></div></div></form></div></div></div>
<div class="col-xl-6"><div class="card h-100"><div class="card-header"><strong>{{ $editingMerchant ? 'Edit' : 'Tambah' }} Data Pedagang</strong></div><div class="card-body">@if($pengelolaOptions->isEmpty())<div class="alert alert-warning mb-0">Tambahkan data pengelola terlebih dahulu.</div>@else<form method="post" action="{{ $editingMerchant ? route('market-data.merchants.update',$editingMerchant) : route('market-data.merchants.store') }}">@csrf @if($editingMerchant)@method('put')@endif<div class="row g-3"><div class="col-12"><label class="form-label">Pengelola</label><select name="pengelola_pasar_id" class="form-select" required>@foreach($pengelolaOptions as $option)<option value="{{ $option->id }}" @selected((string)old('pengelola_pasar_id',$editingMerchant?->pengelola_pasar_id)===(string)$option->id)>{{ $option->nama_perusahaan }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Nama Toko</label><input name="nama_toko" value="{{ old('nama_toko',$editingMerchant?->nama_toko) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Penanggung Jawab</label><input name="penanggung_jawab" value="{{ old('penanggung_jawab',$editingMerchant?->penanggung_jawab) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Nomor Telepon</label><input name="no_telepon" value="{{ old('no_telepon',$editingMerchant?->no_telepon) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Bidang Usaha</label><input name="bidang_usaha" value="{{ old('bidang_usaha',$editingMerchant?->bidang_usaha) }}" class="form-control" required></div><div class="col-md-4"><label class="form-label">Nomor Kios</label><input name="nomor_kios" value="{{ old('nomor_kios',$editingMerchant?->nomor_kios) }}" class="form-control"></div><div class="col-md-8"><label class="form-label">Alamat</label><input name="alamat" value="{{ old('alamat',$editingMerchant?->alamat) }}" class="form-control"></div><div class="col-12 text-end">@if($editingMerchant)<a href="{{ route('market-data.index') }}" class="btn btn-light border me-2">Batal</a>@endif<button class="btn btn-primary">{{ $editingMerchant ? 'Simpan Perubahan' : 'Simpan Pedagang' }}</button></div></div></form>@endif</div></div></div></div>
@endif
@php $labels=['submitted'=>['Menunggu','warning'],'verified'=>['Terverifikasi','success'],'rejected'=>['Ditolak','danger']]; @endphp
@foreach([['Pengelola',$pengelola,'manager'],['Pedagang',$pedagang,'merchant']] as [$title,$rows,$type])
<span id="{{ $type === 'manager' ? 'pengelola' : 'pedagang' }}"></span>
<div class="card mb-4"><div class="card-header"><strong>Data {{ $title }}</strong></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr>@if($type==='manager')<th>Perusahaan</th><th>Alamat</th><th>Telepon</th><th>Kontak Person</th><th>Tenant Aktif / Kapasitas</th>@else<th>Nama Toko</th><th>Pengelola</th><th>Penanggung Jawab</th><th>Telepon</th><th>Bidang Usaha</th><th>Kios</th>@endif<th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($rows as $row)@php $badge=$labels[$row->status]??['Draft','secondary']; @endphp<tr>@if($type==='manager')<td class="fw-semibold">{{ $row->nama_perusahaan }}</td><td>{{ $row->alamat }}</td><td>{{ $row->no_telepon }}</td><td>{{ $row->kontak_person }}</td><td>{{ $row->jumlah_tenant_aktif }} / {{ $row->kapasitas_tenant ?? '—' }}</td>@else<td class="fw-semibold">{{ $row->nama_toko }}</td><td>{{ $row->pengelola->nama_perusahaan }}</td><td>{{ $row->penanggung_jawab }}</td><td>{{ $row->no_telepon }}</td><td>{{ $row->bidang_usaha }}</td><td>{{ $row->nomor_kios ?: '—' }}</td>@endif<td><span class="badge bg-{{ $badge[1] }}-subtle text-{{ $badge[1] }}">{{ $badge[0] }}</span></td><td><div class="d-flex gap-1">@if(auth()->user()->hasPermission('market_data.verify')&&$row->status==='submitted')<form method="post" action="{{ route('market-data.verify',['type'=>$type,'id'=>$row->id]) }}">@csrf<button name="action" value="verify" class="btn btn-sm btn-success">Verifikasi</button></form><form method="post" action="{{ route('market-data.verify',['type'=>$type,'id'=>$row->id]) }}">@csrf<input type="hidden" name="note" value="Data perlu diperbaiki"><button name="action" value="reject" class="btn btn-sm btn-outline-danger">Tolak</button></form>@endif @if(auth()->user()->hasPermission('market_data.create')&&(auth()->user()->isAdmin()||($row->created_by===auth()->id()&&$row->status!=='verified')))<form method="post" action="{{ route('market-data.destroy',['type'=>$type,'id'=>$row->id]) }}" onsubmit="return confirm('Hapus data ini?')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form>@endif</div></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Belum ada data {{ strtolower($title) }}.</td></tr>@endforelse</tbody></table></div></div><div class="mb-4">{{ $rows->links() }}</div>
@endforeach
@push('scripts')
@include('market-data._navigation')
<datalist id="businessTypeSuggestions">@foreach($businessTypes as $businessType)<option value="{{ $businessType }}">@endforeach</datalist>
<script>
document.querySelector('input[name="bidang_usaha"]')?.setAttribute('list','businessTypeSuggestions');
const marketEditGroups=[
    {anchor:'pengelola',param:'edit_manager',rows:@json($managerEditRows)},
    {anchor:'pedagang',param:'edit_merchant',rows:@json($merchantEditRows)}
];
marketEditGroups.forEach(group=>{const table=document.querySelector(`#${group.anchor} + .card table`);if(!table)return;[...table.querySelectorAll('tbody tr')].forEach((row,index)=>{const item=group.rows[index],actions=row.querySelector('td:last-child .d-flex');if(!item?.allowed||!actions)return;const link=document.createElement('a');const url=new URL(@json(route('market-data.index')),window.location.origin);url.searchParams.set(group.param,item.id);url.hash=group.anchor;link.href=url;link.className='btn btn-sm btn-outline-primary';link.innerHTML='<i class="bi bi-pencil"></i> Edit';actions.prepend(link)})});
</script>
@endpush
@endsection
