@extends('layouts.app')
@section('title', 'Laporan Pergerakan Harga')
@section('header', 'Laporan Perdagangan')

@push('styles')
<style>
.movement-paper{max-width:1060px;margin:auto;background:#fff;border:1px solid #dbe5ef;box-shadow:0 10px 30px #092a4b12}.movement-head{background:linear-gradient(115deg,#062e59,#075a98);color:#fff;padding:26px 30px;display:flex;justify-content:space-between;gap:20px;align-items:center}.movement-head h1{font-size:1.55rem;font-weight:850;letter-spacing:.05em;margin:0;text-transform:uppercase}.movement-head p{margin:5px 0 0;color:#cbe9ff}.movement-date{background:#fff;color:#092a4b;border-radius:12px;padding:10px 16px;font-weight:800;text-align:center;min-width:195px}.movement-table th{background:#073a68!important;color:#fff!important;text-align:center!important;vertical-align:middle;font-size:.7rem!important}.movement-table td{font-size:.83rem}.movement-table .today{background:#e2f7ef;font-weight:750}.movement-table .highlight-up{background:#ffe1e1}.movement-table .highlight-down{background:#e4f1bd}.movement-table .highlight-stable{background:#f5f7f9}.movement-summary{display:grid;grid-template-columns:repeat(4,1fr);border-top:7px solid #073a68}.movement-summary>div{padding:16px;text-align:center;border-right:1px solid #d7e1ea}.movement-summary>div:last-child{border:0}.movement-summary strong{display:block;font-size:1.7rem}.up{color:#c62828}.down{color:#208339}.stable{color:#708090}.unavailable{color:#7c8794}.movement-note{padding:12px 22px;background:#f5f8fb;color:#657585;font-size:.76rem}@media(max-width:767px){.movement-head{padding:20px;align-items:flex-start;flex-direction:column}.movement-head h1{font-size:1.15rem}.movement-date{width:100%}.movement-table{min-width:880px}.movement-summary>div{padding:10px 4px;font-size:.7rem}.movement-summary strong{font-size:1.2rem}}@media print{body{background:#fff}.movement-paper{max-width:none;border:0;box-shadow:none}.movement-head{padding:18px 24px}.no-print{display:none!important}@page{size:A4 portrait;margin:8mm}.movement-table td{font-size:8pt;padding:5px}.movement-table th{font-size:7pt;padding:5px}.movement-summary{break-inside:avoid}}
</style>
@endpush

@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4 no-print"><div><h1 class="section-title">Laporan Pergerakan Harga Komoditi</h1><div class="section-subtitle">Rata-rata harga dari seluruh pasar dengan laporan terverifikasi.</div></div><div class="d-flex gap-2"><button type="button" class="btn btn-outline-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>Cetak / Simpan PDF</button><button type="button" class="btn btn-success" id="download-image"><i class="bi bi-image me-1"></i>Unduh PNG</button></div></div>
<form class="card card-body mb-4 no-print" method="get"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Tanggal laporan</label><input type="date" name="report_date" class="form-control" value="{{ $reportDate }}" list="report-dates" required></div><div class="col-md-4"><label class="form-label">Tanggal pembanding</label><input type="date" name="comparison_date" class="form-control" value="{{ $comparisonDate }}" list="report-dates" required></div><div class="col-md-4"><button class="btn btn-primary w-100"><i class="bi bi-arrow-repeat me-1"></i>Tampilkan Laporan</button></div></div><datalist id="report-dates">
@foreach($dates as $date)
<option value="{{ $date->format('Y-m-d') }}"></option>
@endforeach
</datalist></form>

<div id="movement-capture" class="movement-paper">
    <div class="movement-head"><div><h1><i class="bi bi-graph-up-arrow me-2"></i>Laporan Pergerakan Harga Komoditi</h1><p>Dinas Perindustrian dan Perdagangan Kota Batam</p></div><div class="movement-date">{{ $reportDate ? \Carbon\Carbon::parse($reportDate)->locale('id')->translatedFormat('l, d F Y') : 'Pilih tanggal laporan' }}</div></div>
    <div class="px-4 pt-3 small text-muted">Perbandingan dengan <strong>{{ $comparisonDate ? \Carbon\Carbon::parse($comparisonDate)->locale('id')->translatedFormat('d F Y') : '—' }}</strong> · Sumber rata-rata: <strong>{{ $reportMarketCount }} pasar</strong> yang telah diverifikasi pada tanggal laporan.</div>
    <div class="table-responsive px-3 py-3"><table class="table table-bordered mb-0 movement-table"><thead><tr><th rowspan="2">No</th><th rowspan="2" class="text-start">Komoditi</th><th rowspan="2">Satuan</th><th rowspan="2">HET/HA</th><th colspan="2">Harga Rata-rata (Rp)</th><th rowspan="2">Perubahan</th><th rowspan="2">%</th></tr><tr><th>{{ $comparisonDate ? \Carbon\Carbon::parse($comparisonDate)->format('d M') : '—' }}</th><th>{{ $reportDate ? \Carbon\Carbon::parse($reportDate)->format('d M') : '—' }}</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->movement === 'up' ? 'highlight-up' : ($row->movement === 'down' ? 'highlight-down' : ($row->movement === 'stable' ? 'highlight-stable' : '')) }}"><td class="text-center">{{ $loop->iteration }}</td><td><strong>{{ $row->commodity->nama }}</strong><small class="d-block text-muted">{{ $row->market_count ? $row->market_count.' pasar melapor' : 'Belum ada data' }}</small></td><td class="text-center">{{ $row->commodity->satuan?->kode ?? '—' }}</td><td class="text-end">{{ $row->commodity->het_ha !== null ? number_format($row->commodity->het_ha,0,',','.') : '—' }}</td><td class="text-end">{{ $row->comparison !== null ? number_format($row->comparison,0,',','.') : '—' }}</td><td class="text-end today">{{ $row->current !== null ? number_format($row->current,0,',','.') : '—' }}</td><td class="text-center fw-bold {{ $row->movement }}">@if($row->movement === 'up')▲ NAIK (+{{ number_format($row->change,0,',','.') }})@elseif($row->movement === 'down')▼ TURUN ({{ number_format($row->change,0,',','.') }})@elseif($row->movement === 'stable')━ TETAP @else— DATA BELUM LENGKAP@endif</td><td class="text-center fw-bold">{{ $row->percentage !== null ? number_format($row->percentage,2,',','').'%' : '—' }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">Pilih dua tanggal yang mempunyai laporan harga terverifikasi.</td></tr>@endforelse</tbody></table></div>
    <div class="movement-summary"><div class="down"><strong>▼ {{ $summary['down'] }}</strong>TURUN</div><div class="stable"><strong>━ {{ $summary['stable'] }}</strong>TETAP</div><div class="up"><strong>▲ {{ $summary['up'] }}</strong>NAIK</div><div class="unavailable"><strong>— {{ $summary['unavailable'] }}</strong>BELUM LENGKAP</div></div>
    <div class="movement-note">Catatan: harga merupakan rata-rata dari pasar yang melaporkan data tersedia. Komoditas tanpa harga pada salah satu tanggal tidak dihitung sebagai naik, turun, maupun tetap.</div>
</div>
@endsection

@push('scripts')
<script>
document.getElementById('download-image')?.addEventListener('click', async () => { const button = document.getElementById('download-image'); button.disabled = true; button.innerHTML = '<span class="spinner-border spinner-border-sm me-1"></span>Menyiapkan gambar'; try { if (!window.html2canvas) { await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); }); } const canvas = await html2canvas(document.getElementById('movement-capture'), {scale: 2, backgroundColor: '#ffffff', useCORS: true}); const link = document.createElement('a'); link.download = 'laporan-pergerakan-harga-{{ $reportDate ?? 'draft' }}.png'; link.href = canvas.toDataURL('image/png'); link.click(); } catch (error) { alert('Gagal membuat gambar. Periksa koneksi internet lalu coba kembali.'); } finally { button.disabled = false; button.innerHTML = '<i class="bi bi-image me-1"></i>Unduh PNG'; } });
</script>
@endpush
