@extends('layouts.app')
@section('title', 'Laporan Pergerakan Harga')
@section('header', 'Laporan Perdagangan')
@push('styles')
<style>
.paper{max-width:1060px;margin:auto;background:#fff;border:1px solid #dbe5ef}.paper-head{background:#073a68;color:#fff;padding:25px;display:flex;justify-content:space-between;gap:15px}.paper-head h1{font-size:1.4rem;margin:0;font-weight:800}.paper-date{background:#fff;color:#073a68;border-radius:9px;padding:9px 14px;font-weight:700}.price-table th{background:#073a68!important;color:#fff!important;text-align:center;font-size:.7rem}.price-table .today{background:#e2f7ef;font-weight:bold}.up-row{background:#ffe1e1}.down-row{background:#e4f1bd}.summary{display:grid;grid-template-columns:repeat(4,1fr);border-top:6px solid #073a68}.summary div{text-align:center;padding:14px;border-right:1px solid #dbe5ef}.summary strong{display:block;font-size:1.5rem}.up{color:#c62828}.down{color:#208339}.stable{color:#708090}.unavailable{color:#7c8794}@media print{.sidebar,.topbar,.no-print{display:none!important}.main{margin:0}.page{padding:0}.paper{border:0}@page{size:A4 portrait;margin:8mm}}@media(max-width:767px){.paper-head{display:block}.paper-date{margin-top:12px}.price-table{min-width:850px}.summary div{font-size:.7rem;padding:9px}.summary strong{font-size:1.2rem}}
</style>
@endpush
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-2 mb-4 no-print"><div><h1 class="section-title">Laporan Pergerakan Harga Komoditi</h1><div class="section-subtitle">Rata-rata seluruh pasar terverifikasi.</div></div><div><button class="btn btn-outline-primary" onclick="window.print()">Cetak / Simpan PDF</button> <button class="btn btn-success" id="download-image">Unduh PNG</button></div></div>
<form class="card card-body mb-4 no-print" method="get"><div class="row g-3"><div class="col-md-4"><label class="form-label">Tanggal laporan</label><input type="date" name="report_date" class="form-control" value="{{ $reportDate }}" required></div><div class="col-md-4"><label class="form-label">Tanggal pembanding</label><input type="date" name="comparison_date" class="form-control" value="{{ $comparisonDate }}" required></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-primary w-100">Tampilkan Laporan</button></div></div></form>
<div id="capture" class="paper"><div class="paper-head"><div><h1>LAPORAN PERGERAKAN HARGA KOMODITI</h1><div>Dinas Perindustrian dan Perdagangan Kota Batam</div></div><div class="paper-date">{{ $reportDate ? \Carbon\Carbon::parse($reportDate)->locale('id')->translatedFormat('d F Y') : 'Pilih tanggal' }}</div></div><div class="p-3 small text-muted">Perbandingan: {{ $comparisonDate ? \Carbon\Carbon::parse($comparisonDate)->locale('id')->translatedFormat('d F Y') : '-' }} · Sumber: {{ $reportMarketCount }} pasar terverifikasi.</div><div class="table-responsive px-3"><table class="table table-bordered price-table"><thead><tr><th>No</th><th>Komoditi</th><th>Satuan</th><th>HET/HA</th><th>Pembanding</th><th>Hari Ini</th><th>Perubahan</th><th>%</th></tr></thead><tbody>
@forelse($rows as $row)
<tr class="{{ $row->movement === 'up' ? 'up-row' : ($row->movement === 'down' ? 'down-row' : '') }}"><td>{{ $loop->iteration }}</td><td><strong>{{ $row->commodity->nama }}</strong><small class="d-block text-muted">{{ $row->market_count }} pasar melapor</small></td><td>{{ $row->commodity->satuan?->kode ?? '-' }}</td><td>{{ $row->commodity->het_ha !== null ? number_format($row->commodity->het_ha,0,',','.') : '-' }}</td><td>{{ $row->comparison !== null ? number_format($row->comparison,0,',','.') : '-' }}</td><td class="today">{{ $row->current !== null ? number_format($row->current,0,',','.') : '-' }}</td><td class="{{ $row->movement }}">{{ $row->movement === 'up' ? 'NAIK (+'.number_format($row->change,0,',','.').')' : ($row->movement === 'down' ? 'TURUN ('.number_format($row->change,0,',','.').')' : ($row->movement === 'stable' ? 'TETAP' : 'DATA BELUM LENGKAP')) }}</td><td>{{ $row->percentage !== null ? number_format($row->percentage,2,',','').'%' : '-' }}</td></tr>
@empty
<tr><td colspan="8" class="text-center py-5 text-muted">Belum ada data untuk ditampilkan.</td></tr>
@endforelse
</tbody></table></div><div class="summary"><div class="down"><strong>{{ $summary['down'] }}</strong>TURUN</div><div class="stable"><strong>{{ $summary['stable'] }}</strong>TETAP</div><div class="up"><strong>{{ $summary['up'] }}</strong>NAIK</div><div class="unavailable"><strong>{{ $summary['unavailable'] }}</strong>BELUM LENGKAP</div></div></div>
@endsection
@push('scripts')
<script>const formatHeaderDate=value=>value?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short'}).format(new Date(`${value}T00:00:00`)).toUpperCase():'-';document.querySelector('.price-table thead').innerHTML=`<tr><th rowspan="2">No</th><th rowspan="2">Komoditi</th><th rowspan="2">Satuan</th><th rowspan="2">HET/HA</th><th colspan="2">Harga (Rp)</th><th>Perubahan</th><th rowspan="2">%</th></tr><tr><th>${formatHeaderDate('{{ $comparisonDate }}')}</th><th>${formatHeaderDate('{{ $reportDate }}')}</th><th>Naik/Turun/Tetap</th></tr>`;document.getElementById('download-image')?.addEventListener('click',async()=>{try{if(!window.html2canvas)await new Promise((a,b)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';s.onload=a;s.onerror=b;document.head.appendChild(s)});let c=await html2canvas(document.getElementById('capture'),{scale:2,backgroundColor:'#fff'}),a=document.createElement('a');a.download='laporan-harga.png';a.href=c.toDataURL();a.click()}catch(e){alert('Gagal membuat gambar.')}});</script>
@endpush
