@extends('layouts.app')
@section('title','Panduan SIDAGANG')
@section('header','Panduan Pengguna')
@push('styles')
<style>
.guide-cover{padding:30px;border-radius:18px;background:linear-gradient(135deg,#082d4b,#0c70b4);color:#fff}.guide-cover img{width:70px;height:70px;object-fit:contain}.guide-cover p{color:#c8e5f6}.guide-nav{position:sticky;top:94px}.guide-nav a{display:block;padding:8px 0;color:#476174;text-decoration:none;font-size:.85rem}.guide-section{scroll-margin-top:100px}.guide-section h2{font-size:1.25rem;font-weight:800;color:#092a4b}.guide-step{display:flex;gap:13px;padding:12px 0;border-bottom:1px solid #edf1f5}.guide-step:last-child{border:0}.step-no{width:28px;height:28px;flex:none;border-radius:50%;display:grid;place-items:center;background:#e5f2fc;color:#0b6cad;font-weight:800;font-size:.78rem}.role-card{height:100%;border-left:4px solid #176bba}.guide-note{background:#fff8e4;border:1px solid #f5df9c;color:#765d1a;border-radius:11px;padding:13px 15px;font-size:.85rem}@media print{.sidebar,.topbar,.no-print,.guide-nav{display:none!important}.main{margin:0}.page{padding:0}.guide-cover{border-radius:0;break-after:avoid}.card{box-shadow:none}.guide-section{break-inside:avoid}.guide-section h2{margin-top:25px}@page{size:A4;margin:12mm}}
</style>
@endpush
@section('content')
<div class="guide-cover mb-4 d-flex align-items-center justify-content-between gap-3"><div><div class="small fw-bold text-info mb-2">DOKUMEN PENGGUNAAN INTERNAL</div><h1 class="h2 fw-bold mb-2">Panduan SIDAGANG</h1><p class="mb-0">Sistem Informasi Digital Integrasi Perdagangan · Dinas Perindustrian dan Perdagangan Kota Batam</p></div><img src="{{ asset('images/logo-pemko-batam.png') }}" alt="Lambang Kota Batam"></div>
<div class="d-flex justify-content-between align-items-center mb-4 no-print"><div class="text-muted small">Gunakan panduan ini sesuai peran akun Anda.</div><button class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>Cetak / Simpan PDF</button></div>
<div class="row g-4"><aside class="col-lg-3 no-print"><div class="card guide-nav"><div class="card-body"><strong>Daftar Isi</strong><a href="#mulai">Memulai</a><a href="#peran">Peran & akses</a><a href="#perdagangan">Perdagangan</a><a href="#pasar">Bidang Pasar</a><a href="#industri">Perindustrian</a><a href="#metrologi">Metrologi</a><a href="#sekretariat">Sekretariat</a><a href="#admin">Administrasi</a></div></div></aside><main class="col-lg-9">
<section id="mulai" class="guide-section card mb-4"><div class="card-body"><h2>Memulai</h2><div class="guide-step"><span class="step-no">1</span><div><strong>Masuk</strong><div class="text-muted">Buka halaman login, masukkan username dan kata sandi yang diberikan administrator.</div></div></div><div class="guide-step"><span class="step-no">2</span><div><strong>Pilih layanan</strong><div class="text-muted">Gunakan menu sidebar untuk membuka bidang sesuai hak akses akun.</div></div></div><div class="guide-step"><span class="step-no">3</span><div><strong>Simpan dan verifikasi</strong><div class="text-muted">Data harga dan stok perlu dikirim lalu diverifikasi sebelum muncul pada laporan resmi.</div></div></div></div></section>
<section id="peran" class="guide-section mb-4"><h2>Peran dan hak akses</h2><div class="row g-3"><div class="col-md-6"><div class="card role-card"><div class="card-body"><strong>Administrator</strong><p class="small text-muted mb-0">Mengelola seluruh bidang, master data, akun pengguna, peran, dan laporan.</p></div></div></div><div class="col-md-6"><div class="card role-card"><div class="card-body"><strong>Validator</strong><p class="small text-muted mb-0">Memeriksa serta menyetujui atau menolak laporan harga dan stok.</p></div></div></div><div class="col-md-6"><div class="card role-card"><div class="card-body"><strong>Petugas bidang</strong><p class="small text-muted mb-0">Menginput dan mengelola data sesuai bidang yang ditugaskan.</p></div></div></div><div class="col-md-6"><div class="card role-card"><div class="card-body"><strong>Pimpinan</strong><p class="small text-muted mb-0">Melihat dashboard, pemantauan, dan laporan terverifikasi.</p></div></div></div></div></section>
@php($guides = [
['perdagangan','Bidang Perdagangan','Input harga dilakukan per pasar dan tanggal. Pilih status data untuk setiap komoditas, simpan sebagai draft atau kirim untuk verifikasi. Setelah diverifikasi, gunakan menu Laporan Pergerakan Harga untuk membandingkan dua tanggal dan menyimpan PDF/PNG.'],
['pasar','Bidang Pasar','Kelola data pengelola pasar dan pedagang. Isi data secara lengkap, kirim untuk verifikasi bila tersedia, lalu gunakan menu ekspor untuk rekap internal.'],
['industri','Bidang Perindustrian','Tambahkan data IKM melalui menu Data IKM. Lengkapi jenis IKM, produk, tenaga kerja, legalitas, serta omzet. Master dan akun petugas dikelola oleh admin bidang.'],
['metrologi','Tertib Niaga & Metrologi','Pilih jenis kegiatan, masukkan data pelaku usaha dan informasi pemeriksaan atau pelayanan. Gunakan master untuk menjaga pilihan referensi tetap konsisten.'],
['sekretariat','Sekretariat','Catat kegiatan atau dokumen administrasi, pilih jenis data dan status proses, lalu perbarui status hingga selesai atau diarsipkan.'],
['admin','Administrasi Sistem','Administrator mengelola Master Data, akun petugas, dan hak akses. Jangan membagikan akun administrator. Ubah kata sandi bila ada pergantian petugas.'],
])
@foreach($guides as [$id,$title,$text])<section id="{{ $id }}" class="guide-section card mb-4"><div class="card-body"><h2>{{ $title }}</h2><p class="text-muted">{{ $text }}</p><div class="guide-step"><span class="step-no">1</span><div><strong>Buka menu bidang</strong><div class="text-muted">Pilih modul dari sidebar sesuai tugas Anda.</div></div></div><div class="guide-step"><span class="step-no">2</span><div><strong>Lengkapi data</strong><div class="text-muted">Gunakan informasi yang benar dan pastikan kolom wajib terisi.</div></div></div><div class="guide-step"><span class="step-no">3</span><div><strong>Simpan atau ekspor</strong><div class="text-muted">Simpan perubahan, lakukan verifikasi bila diperlukan, dan gunakan ekspor untuk kebutuhan rekap.</div></div></div></div></section>@endforeach
<div class="guide-note"><i class="bi bi-shield-check me-1"></i><strong>Keamanan:</strong> gunakan akun sesuai peran, jangan membagikan kata sandi, dan segera laporkan akses yang tidak dikenal kepada administrator.</div>
</main></div>
@endsection
