<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  foreach(['jenis_ikm'=>['Mikro','Kecil','Menengah'],'skala_industri'=>['Rumahan','Lokal','Regional','Nasional'],'jenis_produk_industri'=>['Makanan dan Minuman','Kerajinan','Tekstil','Logam','Kimia','Elektronik','Lainnya'],'legalitas_industri'=>['NIB','PIRT','Sertifikat Halal','Merek Dagang','Izin Usaha Industri']] as $table=>$values){Schema::create($table,function(Blueprint $t){$t->id();$t->string('nama')->unique();$t->boolean('is_active')->default(true);$t->timestamps();});foreach($values as $value)DB::table($table)->insert(['nama'=>$value,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);}
  Schema::create('data_ikm',function(Blueprint $t){$t->id();$t->string('jenis_ikm');$t->string('skala');$t->string('nama_ikm');$t->string('penanggung_jawab');$t->text('alamat');$t->string('telepon',50);$t->string('jenis_produk');$t->decimal('modal_usaha',18,2)->nullable();$t->decimal('omset',18,2)->nullable();$t->unsignedInteger('jumlah_tenaga_kerja')->default(0);$t->text('legalitas')->nullable();$t->text('keterangan')->nullable();$t->boolean('is_active')->default(true);$t->foreignId('created_by')->constrained('users');$t->timestamps();$t->unique(['nama_ikm','telepon']);});
  $permissions=[['industry.view','Lihat Data Industri'],['industry.create','Kelola Data IKM'],['industry.export','Export Data Industri'],['industry.manage','Kelola Administrasi Industri']];foreach($permissions as[$name,$label])DB::table('permissions')->insertOrIgnore(['name'=>$name,'label'=>$label,'module'=>'Bidang Perindustrian','description'=>$label,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);
  $roleId=DB::table('roles')->insertGetId(['name'=>'petugas_industri','label'=>'Petugas Bidang Perindustrian','description'=>'Petugas pendataan IKM.','created_at'=>now(),'updated_at'=>now()]);$ids=DB::table('permissions')->whereIn('name',array_column($permissions,0))->pluck('id','name');foreach(['industry.view','industry.create','industry.export'] as $name)DB::table('permission_role')->insertOrIgnore(['role_id'=>$roleId,'permission_id'=>$ids[$name]]);foreach(DB::table('roles')->whereIn('name',['super_admin','admin'])->pluck('id') as $adminRole)foreach($ids as $id)DB::table('permission_role')->insertOrIgnore(['role_id'=>$adminRole,'permission_id'=>$id]);
  DB::table('users')->insertOrIgnore(['name'=>'Petugas Bidang Perindustrian','username'=>'petugasindustri','email'=>'industri@sidagang.test','password'=>Hash::make('password'),'role_id'=>$roleId,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);
 }
 public function down():void{DB::table('users')->where('username','petugasindustri')->delete();DB::table('roles')->where('name','petugas_industri')->delete();$ids=DB::table('permissions')->where('name','like','industry.%')->pluck('id');DB::table('permission_role')->whereIn('permission_id',$ids)->delete();DB::table('permissions')->whereIn('id',$ids)->delete();Schema::dropIfExists('data_ikm');foreach(['legalitas_industri','jenis_produk_industri','skala_industri','jenis_ikm']as$table)Schema::dropIfExists($table);}
};
