<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\{DB,Hash,Schema};
return new class extends Migration {
 public function up():void{
  foreach(['lokasi_metrologi'=>['Pasar Tradisional','Pasar Modern','SPBU','Industri','Toko/Ritel'],'kategori_pelaku_usaha'=>['Produsen','Pengemas','Importir','Distributor','Pengecer'],'kategori_bdkt'=>['Makanan','Minuman','Kosmetik','Kebutuhan Rumah Tangga','Lainnya'],'jenis_uttp'=>['Timbangan','Anak Timbangan','Takaran','Meteran','Pompa Ukur BBM','Tangki Ukur','Lainnya']] as $table=>$items){Schema::create($table,function(Blueprint $t){$t->id();$t->string('nama')->unique();$t->boolean('is_active')->default(true);$t->timestamps();});foreach($items as $nama)DB::table($table)->insert(['nama'=>$nama,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);}
  Schema::create('data_metrologi',function(Blueprint $t){$t->id();$t->string('jenis_data');$t->date('tanggal')->nullable();$t->string('lokasi')->nullable();$t->string('nama_pelaku_usaha')->nullable();$t->json('data');$t->boolean('is_active')->default(true);$t->foreignId('created_by')->constrained('users');$t->timestamps();});
  $defs=[['metrology.view','Lihat Data Metrologi'],['metrology.create','Kelola Data Metrologi'],['metrology.export','Ekspor Data Metrologi'],['metrology.manage','Kelola Administrasi Metrologi']];foreach($defs as[$name,$label])DB::table('permissions')->insertOrIgnore(['name'=>$name,'label'=>$label,'module'=>'Tertib Niaga & Metrologi','description'=>$label,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);
  $role=DB::table('roles')->where('name','petugas_metrologi')->value('id')?:DB::table('roles')->insertGetId(['name'=>'petugas_metrologi','label'=>'Petugas Tertib Niaga & Metrologi','description'=>'Petugas pendataan metrologi legal.','created_at'=>now(),'updated_at'=>now()]);$ids=DB::table('permissions')->whereIn('name',array_column($defs,0))->pluck('id','name');foreach(['metrology.view','metrology.create','metrology.export'] as $n)DB::table('permission_role')->insertOrIgnore(['role_id'=>$role,'permission_id'=>$ids[$n]]);foreach(DB::table('roles')->whereIn('name',['super_admin','admin'])->pluck('id') as $r)foreach($ids as $id)DB::table('permission_role')->insertOrIgnore(['role_id'=>$r,'permission_id'=>$id]);DB::table('users')->insertOrIgnore(['name'=>'Petugas Tertib Niaga dan Metrologi','username'=>'petugasmetrologi','email'=>'metrologi@sidagang.test','password'=>Hash::make('password'),'role_id'=>$role,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);
 }
 public function down():void{DB::table('users')->where('username','petugasmetrologi')->delete();Schema::dropIfExists('data_metrologi');foreach(['jenis_uttp','kategori_bdkt','kategori_pelaku_usaha','lokasi_metrologi'] as $t)Schema::dropIfExists($t);}
};
