<?php
namespace App\Http\Controllers;
use App\Models\{MetrologyRecord,Role,User}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule; use PhpOffice\PhpSpreadsheet\Spreadsheet; use PhpOffice\PhpSpreadsheet\Style\{Alignment,Border,Fill}; use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
class MetrologyController extends Controller
{
 public static function types():array{return [
  'inventaris_uttp'=>['Inventaris UTTP',['lokasi'=>'Lokasi','jenis_uttp'=>'Jenis Alat Ukur/Takar/Timbang/Perlengkapan','jumlah'=>'Jumlah Alat','rincian'=>'Jenis dan Jumlah Peralatan','keterangan'=>'Keterangan']],
  'pendataan_bdkt'=>['Pendataan BDKT',['nama_pelaku_usaha'=>'Nama Pelaku Usaha','kategori_pelaku'=>'Kategori Pelaku Usaha','alamat'=>'Alamat Pelaku Usaha','jumlah_bdkt'=>'Jumlah BDKT Diproduksi/Dikemas','nama_barang'=>'Nama Barang/BDKT','kategori_bdkt'=>'Kategori BDKT','kuantitas_nominal'=>'Kata dan Nilai Kuantitas Nominal']],
  'pengawasan_uttp'=>['Pengawasan UTTP',['lokasi'=>'Lokasi','jenis_uttp'=>'Jenis UTTP','jumlah_diawasi'=>'Jumlah Diawasi','tanda_tera'=>'Pemeriksaan Tanda Tera','penggunaan'=>'Penggunaan dan Peruntukan','dokumen'=>'Pemeriksaan Dokumen','jumlah_memenuhi'=>'Jumlah Memenuhi Ketentuan','bukti'=>'Link Bukti Pengawasan']],
  'pengawasan_bdkt'=>['Pengawasan BDKT',['nama_pelaku_usaha'=>'Nama Pelaku Usaha','kategori_pelaku'=>'Kategori Pelaku Usaha','alamat'=>'Alamat Pelaku Usaha','nama_barang'=>'Nama Barang','kuantitas_nominal'=>'Nilai Kuantitas Nominal','jumlah_produk'=>'Jumlah Produk','jumlah_sampel'=>'Jumlah Sampel','pelabelan_sesuai'=>'Pelabelan Sesuai','pelabelan_tidak'=>'Pelabelan Tidak Sesuai','kuantitas_diterima'=>'Kuantitas Diterima','kuantitas_ditolak'=>'Kuantitas Ditolak','jumlah_memenuhi'=>'Jumlah Memenuhi Ketentuan','bukti'=>'Link Bukti Pengawasan']],
  'layanan_metrologi'=>['Layanan Metrologi',['nama_perusahaan'=>'Nama Perusahaan','alamat'=>'Alamat','jenis_uttp'=>'Jenis UTTP','jatuh_tempo'=>'Tanggal Jatuh Tempo SKTTP']]
 ];}
 private array $masters=['lokasi_metrologi'=>'Lokasi','kategori_pelaku_usaha'=>'Kategori Pelaku Usaha','kategori_bdkt'=>'Kategori BDKT','jenis_uttp'=>'Jenis UTTP'];
 public function dashboard(){return view('metrology.dashboard',['total'=>MetrologyRecord::count(),'bulan'=>MetrologyRecord::whereMonth('tanggal',now()->month)->count(),'pelaku'=>MetrologyRecord::whereNotNull('nama_pelaku_usaha')->distinct()->count('nama_pelaku_usaha'),'types'=>collect(self::types())->map(fn($v,$k)=>['key'=>$k,'label'=>$v[0],'count'=>MetrologyRecord::where('jenis_data',$k)->count()])]);}
 public function index(Request $r){$type=array_key_exists($r->type,self::types())?$r->type:'inventaris_uttp';$q=trim((string)$r->q);$rows=MetrologyRecord::where('jenis_data',$type)->when($q,fn($x)=>$x->where(fn($y)=>$y->where('lokasi','like',"%$q%")->orWhere('nama_pelaku_usaha','like',"%$q%")->orWhere('data','like',"%$q%")))->latest()->paginate(15)->withQueryString();$edit=$r->filled('edit')?MetrologyRecord::where('jenis_data',$type)->findOrFail($r->integer('edit')):null;return view('metrology.index',['types'=>self::types(),'type'=>$type,'definition'=>self::types()[$type],'rows'=>$rows,'edit'=>$edit,'q'=>$q,'masters'=>$this->masterValues()]);}
 public function store(Request $r){$type=$this->validType($r->jenis_data);MetrologyRecord::create($this->recordData($r,$type)+['created_by'=>$r->user()->id]);return back()->with('success','Data metrologi berhasil disimpan.');}
 public function update(Request $r,MetrologyRecord $record){$record->update($this->recordData($r,$record->jenis_data));return redirect()->route('metrology.index',['type'=>$record->jenis_data])->with('success','Data berhasil diperbarui.');}
 public function destroy(MetrologyRecord $record){$record->delete();return back()->with('success','Data berhasil dihapus.');}
 public function master(){$groups=collect($this->masters)->mapWithKeys(fn($label,$table)=>[$table=>['label'=>$label,'rows'=>DB::table($table)->orderBy('nama')->get()]]);return view('metrology.master',compact('groups'));}
 public function storeMaster(Request $r,string $type){$this->masterTable($type);$d=$r->validate(['nama'=>['required','string','max:150',Rule::unique($type)]]);DB::table($type)->insert($d+['is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Master data ditambahkan.');}
 public function updateMaster(Request $r,string $type,int $id){$this->masterTable($type);$d=$r->validate(['nama'=>['required','string','max:150',Rule::unique($type)->ignore($id)]]);DB::table($type)->where('id',$id)->update($d+['updated_at'=>now()]);return back()->with('success','Master data diperbarui.');}
 public function toggleMaster(string $type,int $id){$this->masterTable($type);$x=DB::table($type)->find($id);abort_unless($x,404);DB::table($type)->where('id',$id)->update(['is_active'=>!$x->is_active,'updated_at'=>now()]);return back()->with('success','Status master diperbarui.');}
 public function accounts(){$role=Role::where('name','petugas_metrologi')->firstOrFail();return view('metrology.accounts',['users'=>User::where('role_id',$role->id)->orderBy('name')->get()]);}
 public function storeAccount(Request $r){$d=$r->validate(['name'=>'required|string|max:150','username'=>'required|alpha_dash|max:100|unique:users','email'=>'nullable|email|max:150|unique:users','password'=>'required|string|min:8|confirmed']);User::create($d+['role_id'=>Role::where('name','petugas_metrologi')->value('id'),'is_active'=>true]);return back()->with('success','Akun petugas berhasil dibuat.');}
 public function toggleAccount(User $user){abort_unless($user->role?->name==='petugas_metrologi',404);$user->update(['is_active'=>!$user->is_active]);return back()->with('success','Status akun diperbarui.');}
 public function excel(){ $book=new Spreadsheet;$book->removeSheetByIndex(0);foreach(self::types() as $key=>[$label,$fields]){$s=$book->createSheet();$s->setTitle(substr($label,0,31));$headers=array_merge(['No','Tanggal'],array_values($fields));$s->fromArray([strtoupper($label)],null,'A1');$s->fromArray($headers,null,'A3');foreach(MetrologyRecord::where('jenis_data',$key)->orderBy('tanggal')->get() as $i=>$r){$values=[$i+1,$r->tanggal?->format('d/m/Y')];foreach(array_keys($fields) as $f)$values[]=$r->data[$f]??($f==='lokasi'?$r->lokasi:($f==='nama_pelaku_usaha'?$r->nama_pelaku_usaha:''));$s->fromArray($values,null,'A'.($i+4));}$lastCol=$s->getHighestColumn();$last=max(3,$s->getHighestRow());$s->mergeCells("A1:{$lastCol}1");$s->getStyle("A1:{$lastCol}1")->applyFromArray(['font'=>['bold'=>true,'size'=>15,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>'075E66']],'alignment'=>['horizontal'=>Alignment::HORIZONTAL_CENTER]]);$s->getStyle("A3:{$lastCol}3")->applyFromArray(['font'=>['bold'=>true,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>'128C7E']],'alignment'=>['wrapText'=>true,'horizontal'=>Alignment::HORIZONTAL_CENTER]]);$s->getStyle("A3:{$lastCol}{$last}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);foreach(range('A',$lastCol) as $c)$s->getColumnDimension($c)->setAutoSize(true);$s->freezePane('A4');$s->setAutoFilter("A3:{$lastCol}{$last}");}$book->setActiveSheetIndex(0);return response()->streamDownload(fn()=>(new Xlsx($book))->save('php://output'),'data-tertib-niaga-metrologi-'.now()->format('Y-m-d').'.xlsx',['Content-Type'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);}
 private function recordData(Request $r,string $type):array{$r->validate(['tanggal'=>'nullable|date']);$fields=array_keys(self::types()[$type][1]);$data=[];foreach($fields as $f)$data[$f]=$r->input($f);return ['jenis_data'=>$type,'tanggal'=>$r->tanggal,'lokasi'=>$data['lokasi']??null,'nama_pelaku_usaha'=>$data['nama_pelaku_usaha']??$data['nama_perusahaan']??null,'data'=>$data];}
 private function validType(?string $type):string{abort_unless($type&&array_key_exists($type,self::types()),422);return $type;} private function masterTable(string $t):void{abort_unless(array_key_exists($t,$this->masters),404);} private function masterValues(){return collect($this->masters)->mapWithKeys(fn($l,$t)=>[$t=>DB::table($t)->where('is_active',true)->orderBy('nama')->pluck('nama')]);}
}
