<?php
namespace App\Http\Controllers;
use App\Models\{Role,SecretariatRecord,User};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use PhpOffice\PhpSpreadsheet\Spreadsheet;use PhpOffice\PhpSpreadsheet\Style\{Alignment,Border,Fill};use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
class SecretariatController extends Controller{
 public static function types():array{return[
 'surat'=>['Surat Masuk & Keluar',['arah_surat'=>'Jenis Surat','nomor_surat'=>'Nomor Surat','asal_tujuan'=>'Asal/Tujuan Surat','perihal'=>'Perihal','disposisi'=>'Disposisi','status'=>'Status Tindak Lanjut','keterangan'=>'Keterangan']],
 'agenda'=>['Agenda & Kegiatan',['waktu'=>'Waktu','lokasi'=>'Lokasi','penanggung_jawab'=>'Penanggung Jawab','peserta'=>'Peserta','status'=>'Status Kegiatan','dokumentasi'=>'Link Dokumentasi','keterangan'=>'Keterangan']],
 'dokumen'=>['Dokumen Administrasi',['jenis_dokumen'=>'Jenis Dokumen','nomor_dokumen'=>'Nomor Dokumen','tahun'=>'Tahun','unit_kerja'=>'Unit Pemilik','masa_berlaku'=>'Masa Berlaku','status'=>'Status','tautan_berkas'=>'Tautan Berkas','uraian'=>'Uraian']],
 'inventaris'=>['Inventaris & ATK',['kode_barang'=>'Kode Barang','nama_barang'=>'Nama Barang','kategori'=>'Kategori','satuan'=>'Satuan','jumlah'=>'Jumlah/Stok','kondisi'=>'Kondisi','lokasi'=>'Lokasi','penanggung_jawab'=>'Penanggung Jawab','unit_kerja'=>'Unit Kerja','keterangan'=>'Keterangan']]];}
 private array $masters=['jenis_dokumen_sekretariat'=>'Jenis Dokumen','unit_kerja_sekretariat'=>'Unit Kerja','status_administrasi'=>'Status Administrasi','satuan_atk'=>'Satuan ATK'];
 public function dashboard(){return view('secretariat.dashboard-branded',['total'=>SecretariatRecord::count(),'bulan'=>SecretariatRecord::whereMonth('tanggal',now()->month)->count(),'proses'=>SecretariatRecord::whereNotIn('status',['Selesai','Diarsipkan'])->whereNotNull('status')->count(),'types'=>collect(self::types())->map(fn($v,$k)=>['key'=>$k,'label'=>$v[0],'count'=>SecretariatRecord::where('jenis_data',$k)->count()])]);}
 public function index(Request $r){$type=array_key_exists($r->type,self::types())?$r->type:'surat';$q=trim((string)$r->q);$rows=SecretariatRecord::where('jenis_data',$type)->when($q,fn($x)=>$x->where(fn($y)=>$y->where('judul','like',"%$q%")->orWhere('unit_kerja','like',"%$q%")->orWhere('data','like',"%$q%")))->latest()->paginate(15)->withQueryString();$edit=$r->filled('edit')?SecretariatRecord::where('jenis_data',$type)->findOrFail($r->integer('edit')):null;return view('secretariat.index',['types'=>self::types(),'type'=>$type,'definition'=>self::types()[$type],'rows'=>$rows,'edit'=>$edit,'q'=>$q,'masters'=>$this->masterValues()]);}
 public function store(Request $r){$type=$this->validType($r->jenis_data);SecretariatRecord::create($this->recordData($r,$type)+['created_by'=>$r->user()->id]);return back()->with('success','Data sekretariat berhasil disimpan.');}public function update(Request $r,SecretariatRecord $record){$record->update($this->recordData($r,$record->jenis_data));return redirect()->route('secretariat.index',['type'=>$record->jenis_data])->with('success','Data berhasil diperbarui.');}public function destroy(SecretariatRecord $record){$record->delete();return back()->with('success','Data berhasil dihapus.');}
 public function master(){$groups=collect($this->masters)->mapWithKeys(fn($l,$t)=>[$t=>['label'=>$l,'rows'=>DB::table($t)->orderBy('nama')->get()]]);return view('secretariat.master',compact('groups'));}public function storeMaster(Request $r,string $type){$this->masterTable($type);$d=$r->validate(['nama'=>['required','string','max:150',Rule::unique($type)]]);DB::table($type)->insert($d+['is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Master data ditambahkan.');}public function updateMaster(Request $r,string $type,int $id){$this->masterTable($type);$d=$r->validate(['nama'=>['required','string','max:150',Rule::unique($type)->ignore($id)]]);DB::table($type)->where('id',$id)->update($d+['updated_at'=>now()]);return back()->with('success','Master data diperbarui.');}public function toggleMaster(string $type,int $id){$this->masterTable($type);$x=DB::table($type)->find($id);abort_unless($x,404);DB::table($type)->where('id',$id)->update(['is_active'=>!$x->is_active,'updated_at'=>now()]);return back()->with('success','Status master diperbarui.');}
 public function accounts(){$role=Role::where('name','petugas_sekretariat')->firstOrFail();return view('secretariat.accounts',['users'=>User::where('role_id',$role->id)->orderBy('name')->get()]);}public function storeAccount(Request $r){$d=$r->validate(['name'=>'required|string|max:150','username'=>'required|alpha_dash|max:100|unique:users','email'=>'nullable|email|max:150|unique:users','password'=>'required|string|min:8|confirmed']);User::create($d+['role_id'=>Role::where('name','petugas_sekretariat')->value('id'),'is_active'=>true]);return back()->with('success','Akun petugas dibuat.');}public function toggleAccount(User $user){abort_unless($user->role?->name==='petugas_sekretariat',404);$user->update(['is_active'=>!$user->is_active]);return back()->with('success','Status akun diperbarui.');}
 public function excel(){$book=new Spreadsheet;$book->removeSheetByIndex(0);foreach(self::types() as$key=>[$label,$fields]){$s=$book->createSheet();$s->setTitle(substr($label,0,31));$s->fromArray([strtoupper($label)],null,'A1');$s->fromArray(array_merge(['No','Tanggal','Judul/Nama'],array_values($fields)),null,'A3');foreach(SecretariatRecord::where('jenis_data',$key)->orderBy('tanggal')->get()as$i=>$r){$v=[$i+1,$r->tanggal?->format('d/m/Y'),$r->judul];foreach(array_keys($fields)as$f)$v[]=$r->data[$f]??'';$s->fromArray($v,null,'A'.($i+4));}$lc=$s->getHighestColumn();$lr=max(3,$s->getHighestRow());$s->mergeCells("A1:{$lc}1");$s->getStyle("A1:{$lc}1")->applyFromArray(['font'=>['bold'=>true,'size'=>15,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>'173F67']],'alignment'=>['horizontal'=>Alignment::HORIZONTAL_CENTER]]);$s->getStyle("A3:{$lc}3")->applyFromArray(['font'=>['bold'=>true,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>'2D6594']],'alignment'=>['wrapText'=>true,'horizontal'=>Alignment::HORIZONTAL_CENTER]]);$s->getStyle("A3:{$lc}{$lr}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);foreach(range('A',$lc)as$c)$s->getColumnDimension($c)->setAutoSize(true);$s->freezePane('A4');$s->setAutoFilter("A3:{$lc}{$lr}");}$book->setActiveSheetIndex(0);return response()->streamDownload(fn()=>(new Xlsx($book))->save('php://output'),'data-sekretariat-'.now()->format('Y-m-d').'.xlsx',['Content-Type'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);}
 private function recordData(Request$r,string$type):array{$r->validate(['tanggal'=>'nullable|date','judul'=>'required|string|max:255']);$data=[];foreach(array_keys(self::types()[$type][1])as$f)$data[$f]=$r->input($f);return['jenis_data'=>$type,'tanggal'=>$r->tanggal,'judul'=>$r->judul,'unit_kerja'=>$data['unit_kerja']??null,'status'=>$data['status']??null,'data'=>$data];}private function validType(?string$t):string{abort_unless($t&&array_key_exists($t,self::types()),422);return$t;}private function masterTable(string$t):void{abort_unless(array_key_exists($t,$this->masters),404);}private function masterValues(){return collect($this->masters)->mapWithKeys(fn($l,$t)=>[$t=>DB::table($t)->where('is_active',true)->orderBy('nama')->pluck('nama')]);}
}
